# Data Cleaning and Preprocessing

**Internship:** Oasis Infobyte – AICTE Data Analytics Internship  
**Task:** Level 1 – Task 3  
**Name:** Prajwal Poojary

## Objective
To identify and correct data quality issues, handle missing values and duplicate records, standardise inconsistent data, detect outliers, and produce a clean, analysis-ready dataset.

## Tools and Technologies
- Python
- pandas
- NumPy
- Jupyter Notebook

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Dirty-customers.csv")

df.head()

,customer_id,full_name,email,signup_date,country,spend,segment,is_active
0,CUST-1387,Aisha Brennan,aisha.brennan@mail.test,NaN,Germany,-,enterprise,N
1,CUST-1943,omar Brennan,omar.brennan@example.com,25 Jan 2025,uk,$100.66,enterprise,N
2,CUST-1007,ravi okafor,ravi[at]example.com,2024-10-18,Brazil,$273.67,ENT,1
3,CUST-1249,Leilani da silva,leilani.dasilva@corp.example,"Jun 26, 2024",United Kingdom,$84.38,Mid-Market,yes
4,CUST-1900,Marcus Kowalski,marcus.kowalski@example.com,"Sep 26, 2024",germany,NaN,midmarket,true

In [3]:
print("Dataset shape:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nDataset information:")
df.info()

Dataset shape: (1000, 8)

Column names:
['customer_id', 'full_name', 'email', 'signup_date', 'country', 'spend', 'segment', 'is_active']

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  1000 non-null   object
 1   full_name    1000 non-null   object
 2   email        969 non-null    object
 3   signup_date  969 non-null    object
 4   country      1000 non-null   object
 5   spend        962 non-null    object
 6   segment      1000 non-null   object
 7   is_active    1000 non-null   object
dtypes: object(8)
memory usage: 62.6+ KB

In [4]:
print("Missing values per column:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

print("\nTotal rows:", len(df))
print("Total columns:", len(df.columns))

Missing values per column:
customer_id     0
full_name       0
email          31
signup_date    31
country         0
spend          38
segment         0
is_active       0
dtype: int64

Duplicate rows: 1

Total rows: 1000
Total columns: 8

In [5]:
for column in df.columns:
    print(f"\n--- {column} ---")
    print(df[column].value_counts(dropna=False).head(15))

--- customer_id ---
customer_id
CUST-1391        3
CUST-00001793    2
CUST-1039        2
CUST-1063        2
CUST-1584        2
CUST-1694        2
CUST-00001302    2
CUST-1040        2
CUST-1518        2
CUST-00001157    2
CUST-1639        2
CUST-1313        2
CUST-00001215    2
CUST-1615        2
CUST-1161        2
Name: count, dtype: int64

--- full_name ---
full_name
Grace Nakamura     9
Yuki weber         9
Aisha Ferrari      9
Mikael Ferrari     8
Sofia Kowalski     8
Grace Nguyen       8
ravi Nakamura      8
PRIYA Nakamura     8
omar Nakamura      8
jonas Ferrari      7
ravi Nguyen        7
ravi Costa         7
Leilani Ferrari    7
Noor Nakamura      7
ravi Kowalski      7
Name: count, dtype: int64

--- email ---
email
NaN                             31
grace.ferrari@mail.test          7
aisha.odwyer@mail.test           6
grace.nakamura@mail.test         5
jonas.ferrari@corp.example       5
aisha.ferrari@mail.test          5
grace.nguyen@example.com         5
yuki.weber@corp.example          5
omar.nakamura@mail.test          5
noor.dasilva@mail.test           5
noor.kowalski@mail.test          4
grace.lindqvist@corp.example     4
ravi.costa@example.com           4
ana.patel@mail.test              4
mikael.ferrari@example.com       4
Name: count, dtype: int64

--- signup_date ---
signup_date
NaN             31
none            12
-                7
06/21/2023       4
-999             4
13 Jul 2024      3
Apr 19, 2025     3
02/07/2024       3
16 Apr 2023      3
2023-11-19       3
02.09.2024       3
04/18/2023       3
May 16, 2023     3
06.03.2024       3
2025-04-21       3
Name: count, dtype: int64

--- country ---
country
Brazil            84
u.s.              83
US                76
FR                75
GB                73
uk                71
Germany           71
usa               70
BR                70
DE                68
france            68
United States     65
germany           63
United Kingdom    63
Name: count, dtype: int64

--- spend ---
spend
NaN           38
-999          10
-              9
none           5
540            3
284            3
236            3
93             3
77             3
$48.17         3
321            3
137.74         2
144            2
USD 596.05     2
$268.81        2
Name: count, dtype: int64

--- segment ---
segment
smb               106
enterprise        105
ENT                99
midmarket          98
SMB                96
consumer           86
Mid-Market         85
Consumer           81
Mid Market         80
Small Business     75
Enterprise         74
ent                 5
small business      4
mid-market          3
mid market          3
Name: count, dtype: int64

--- is_active ---
is_active
FALSE    113
Y        106
false    105
yes      103
TRUE     101
1         98
no        98
0         95
N         93
true      88
Name: count, dtype: int64

### Initial Data Quality Findings

The initial inspection identified the following issues:

- Missing values in `email`, `signup_date`, and `spend`.
- Duplicate records and repeated customer IDs requiring further investigation.
- Inconsistent name capitalisation, country labels, customer segments, and active-status values.
- Mixed date formats and invalid date placeholders such as `none`, `-`, and `-999`.
- Spending values stored as text, including currency symbols, missing-value placeholders, and negative sentinel values.
- All columns currently use the `object` data type, so appropriate data types must be established during cleaning.

These issues will be investigated before applying cleaning operations. Repeated customer IDs will not automatically be treated as duplicate rows because a customer may have multiple records.

In [6]:
print("Original data types:")
print(df.dtypes)

print("\nUnique active-status values:")
print(sorted(df["is_active"].dropna().unique()))

print("\nUnique segment values:")
print(sorted(df["segment"].dropna().unique()))

print("\nSample spending values:")
print(df["spend"].dropna().sample(min(20, df["spend"].notna().sum()), random_state=42).tolist())

Original data types:
customer_id    object
full_name      object
email          object
signup_date    object
country        object
spend          object
segment        object
is_active      object
dtype: object

Unique active-status values:
['0', '1', 'FALSE', 'N', 'TRUE', 'Y', 'false', 'no', 'true', 'yes']

Unique segment values:
['Consumer', 'ENT', 'Enterprise', 'Mid Market', 'Mid-Market', 'SMB ', 'Small Business', 'consumer', 'ent', 'enterprise', 'mid market', 'mid-market', 'midmarket', 'small business', 'smb']

Sample spending values:
['$195.53', '199', '113.29', 'USD 126.8', '243.23', '29694', 'USD 864.54', 'USD 107.31', '1,007', '$39.82', '405.54', 'USD 52.22', '114', 'USD 147.89', '212.38', '214', '209', '$226.11', '-', 'USD 206.59']

In [7]:
spend_text = df["spend"].astype("string").str.strip()

print("Spending placeholders:")
print(
    spend_text[
        spend_text.str.lower().isin(["", "-", "none", "null", "nan", "-999"])
    ].value_counts(dropna=False)
)

print("\nExamples of spending values:")
print(spend_text.dropna().unique()[:30])

Spending placeholders:
spend
-999    10
-        9
none     5
Name: count, dtype: Int64

Examples of spending values:
<StringArray>
[         '-',    '$100.66',    '$273.67',     '$84.38',     '122.09',
 'USD 139.54',    '$461.54',    '$341.62',    '$242.52',     '136.26',
    '$189.67',        '751',      '44518',         '65',    '1652.39',
      '238.7',       '-999',     '130.12',    '$672.66',         '54',
       '6630',   'USD 92.2',    '$398.01', 'USD 419.49',    'USD 445',
 'USD 455.31', 'USD 108.58',        '223',      '11097',      '46753']
Length: 30, dtype: string

In [8]:
spend_clean = (
    df["spend"]
    .astype("string")
    .str.strip()
    .str.replace(r"(?i)^USD\s*", "", regex=True)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
)

spend_clean = spend_clean.replace(
    r"(?i)^\s*(?:-|none|null|nan|-999)?\s*$",
    pd.NA,
    regex=True
)

spend_numeric = pd.to_numeric(spend_clean, errors="coerce")

print("Valid numeric spending values:", spend_numeric.notna().sum())
print("Unusable or missing values:", spend_numeric.isna().sum())

print("\nSpending summary:")
print(spend_numeric.describe())

print("\nLargest 15 spending values:")
print(spend_numeric.nlargest(15).to_list())

Valid numeric spending values: 938
Unusable or missing values: 62

Spending summary:
count           938.0
mean      4808.889627
std      15675.281135
min             15.04
25%           128.695
50%           252.495
75%            629.75
max          171623.0
Name: spend, dtype: Float64

Largest 15 spending values:
[171623.0, 171623.0, 132327.0, 108798.0, 100223.0, 85593.0, 80337.0, 78491.0, 77921.0, 75825.0, 73744.0, 73335.0, 67496.0, 64607.0, 64412.0]

In [9]:
Q1 = spend_numeric.quantile(0.25)
Q3 = spend_numeric.quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = spend_numeric[
    (spend_numeric < lower_bound) |
    (spend_numeric > upper_bound)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)
print("Number of outliers:", len(outliers))

print("\nLargest detected outliers:")
print(outliers.nlargest(10).to_list())

Q1: 128.695
Q3: 629.75
IQR: 501.055
Lower bound: -622.8875
Upper bound: 1381.3325
Number of outliers: 150

Largest detected outliers:
[171623.0, 171623.0, 132327.0, 108798.0, 100223.0, 85593.0, 80337.0, 78491.0, 77921.0, 75825.0]

In [10]:
outlier_rows = df.loc[
    spend_numeric > upper_bound,
    ["customer_id", "full_name", "spend"]
].copy()

outlier_rows["numeric_spend"] = spend_numeric.loc[outlier_rows.index]

outlier_rows.sort_values(
    "numeric_spend", ascending=False
).head(20)

       customer_id        full_name   spend  numeric_spend
876      CUST-1269      Yuki haddad  171623       171623.0
548      CUST-1269     YUKI HADDAD   171623       171623.0
923      CUST-1732   Leilani ODWYER  132327       132327.0
325      CUST-1869    Mikael Nguyen  108798       108798.0
906  CUST-00001403    Leilani Costa  100223       100223.0
403      CUST-1566   Yuki Lindqvist   85593        85593.0
659      CUST-1663       Noor weber   80337        80337.0
372  CUST-00001794    PRIYA Ferrari   78491        78491.0
605      CUST-1833    Yuki Nakamura   77921        77921.0
115      CUST-1774  omar da silva     75825        75825.0
958      CUST-1256    omar Nakamura   73744        73744.0
717      CUST-1680      omar haddad   73335        73335.0
671      CUST-1399    Yuki Kowalski   67496        67496.0
295      CUST-1388   Noor Brennan     64607        64607.0
895      CUST-1207     ravi Brennan   64412        64412.0
742  CUST-00001082     Marcus weber   63544        63544.0
882      CUST-1497    Aisha Ferrari   62599        62599.0
455      CUST-1214       omar weber   62538        62538.0
293      CUST-1778    Noor Kowalski   60600        60600.0
938  CUST-00001517     Yuki Ferrari   58405        58405.0

In [11]:
duplicate_rows = df[df.duplicated(keep=False)].sort_values("customer_id")

duplicate_rows

,customer_id,full_name,email,signup_date,country,spend,segment,is_active
297,CUST-1391,NOOR OKAFOR,NOOR.OKAFOR@EXAMPLE.COM,13 Jul 2024,uk,$48.17,enterprise,no
518,CUST-1391,NOOR OKAFOR,NOOR.OKAFOR@EXAMPLE.COM,13 Jul 2024,uk,$48.17,enterprise,no

In [12]:
df_clean = df.drop_duplicates().copy()

print("Rows before cleaning:", len(df))
print("Rows after duplicate removal:", len(df_clean))
print("Duplicate rows removed:", len(df) - len(df_clean))
print("Remaining duplicate rows:", df_clean.duplicated().sum())

Rows before cleaning: 1000
Rows after duplicate removal: 999
Duplicate rows removed: 1
Remaining duplicate rows: 0

In [13]:
for column in df_clean.columns:
    placeholders = df_clean[column].astype("string").str.strip().str.lower().isin(
        ["", "none", "null", "nan", "-"]
    )

    print(f"{column}: {placeholders.sum()} placeholder values")

customer_id: 0 placeholder values
full_name: 0 placeholder values
email: 0 placeholder values
signup_date: 19 placeholder values
country: 0 placeholder values
spend: 14 placeholder values
segment: 0 placeholder values
is_active: 0 placeholder values

In [14]:
print("Actual missing values:")
print(df_clean.isna().sum())

print("\nDate placeholders:")
print(
    df_clean["signup_date"]
    .astype("string")
    .str.strip()
    .str.lower()
    .value_counts()
    .reindex(["none", "-", "-999"], fill_value=0)
)

print("\nSpending placeholders:")
print(
    df_clean["spend"]
    .astype("string")
    .str.strip()
    .str.lower()
    .value_counts()
    .reindex(["none", "-", "-999"], fill_value=0)
)

Actual missing values:
customer_id     0
full_name       0
email          31
signup_date    31
country         0
spend          38
segment         0
is_active       0
dtype: int64

Date placeholders:
signup_date
none    12
-        7
-999     4
Name: count, dtype: Int64

Spending placeholders:
spend
none     5
-        9
-999    10
Name: count, dtype: Int64

In [15]:
df_clean["signup_date"] = df_clean["signup_date"].replace(
    ["none", "-", "-999"], np.nan, regex=False
)

df_clean["spend"] = df_clean["spend"].replace(
    ["none", "-", "-999"], np.nan, regex=False
)

print("Missing values after placeholder cleaning:")
print(df_clean.isna().sum())

Missing values after placeholder cleaning:
customer_id     0
full_name       0
email          31
signup_date    54
country         0
spend          62
segment         0
is_active       0
dtype: int64

In [16]:
# Convert spending values into a consistent numeric format
spend_text = (
    df_clean["spend"]
    .astype("string")
    .str.strip()
    .str.replace(r"(?i)USD\s*", "", regex=True)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
)

df_clean["spend"] = pd.to_numeric(spend_text, errors="coerce")

print("Spending data type:", df_clean["spend"].dtype)
print("\nSpending summary:")
print(df_clean["spend"].describe())

Spending data type: Float64

Spending summary:
count           937.0
mean      4813.970438
std      15682.879649
min             15.04
25%            129.31
50%            252.99
75%             630.0
max          171623.0
Name: spend, dtype: Float64

In [17]:
# Calculate IQR boundaries
Q1 = df_clean["spend"].quantile(0.25)
Q3 = df_clean["spend"].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identify outliers
outliers = df_clean[
    (df_clean["spend"] < lower_bound) |
    (df_clean["spend"] > upper_bound)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)
print("Number of outliers:", len(outliers))
print("\nLargest spending values:")
print(outliers["spend"].nlargest(10).to_list())

Q1: 129.31
Q3: 630.0
IQR: 500.69
Lower bound: -621.7249999999999
Upper bound: 1381.0349999999999
Number of outliers: 150

Largest spending values:
[171623.0, 171623.0, 132327.0, 108798.0, 100223.0, 85593.0, 80337.0, 78491.0, 77921.0, 75825.0]

In [18]:
# Record outliers before capping
outlier_count_before = len(outliers)

# Cap unusually high spending values at the IQR upper bound
df_clean["spend"] = df_clean["spend"].clip(upper=upper_bound)

print("Outliers identified before capping:", outlier_count_before)
print("Upper capping limit:", round(upper_bound, 2))
print("Maximum spending after capping:", df_clean["spend"].max())
print("Missing spending values:", df_clean["spend"].isna().sum())

Outliers identified before capping: 150
Upper capping limit: 1381.04
Maximum spending after capping: 1381.0349999999999
Missing spending values: 62

In [19]:
# Calculate the median of the cleaned spending values
spend_median = df_clean["spend"].median()

# Fill missing spending values with the median
df_clean["spend"] = df_clean["spend"].fillna(spend_median)

print("Median used for imputation:", round(spend_median, 2))
print("Missing spending values remaining:", df_clean["spend"].isna().sum())
print("Spending data type:", df_clean["spend"].dtype)

Median used for imputation: 252.99
Missing spending values remaining: 0
Spending data type: Float64

In [20]:
# Standardise country names
df_clean["country"] = df_clean["country"].astype("string").str.strip().str.lower()

country_mapping = {
    "us": "United States",
    "u.s.": "United States",
    "usa": "United States",
    "united states": "United States",
    "uk": "United Kingdom",
    "gb": "United Kingdom",
    "united kingdom": "United Kingdom",
    "fr": "France",
    "france": "France",
    "de": "Germany",
    "germany": "Germany",
    "br": "Brazil",
    "brazil": "Brazil"
}

df_clean["country"] = df_clean["country"].replace(country_mapping)

print(df_clean["country"].value_counts())

country
United States     294
United Kingdom    206
Germany           202
Brazil            154
France            143
Name: count, dtype: Int64

In [21]:
# Standardise customer segment labels
df_clean["segment"] = (
    df_clean["segment"]
    .astype("string")
    .str.strip()
    .str.lower()
)

segment_mapping = {
    "smb": "Small Business",
    "small business": "Small Business",
    "consumer": "Consumer",
    "ent": "Enterprise",
    "enterprise": "Enterprise",
    "midmarket": "Mid-Market",
    "mid-market": "Mid-Market",
    "mid market": "Mid-Market"
}

df_clean["segment"] = df_clean["segment"].replace(segment_mapping)

print(df_clean["segment"].value_counts())

segment
Enterprise        282
Small Business    281
Mid-Market        269
Consumer          167
Name: count, dtype: Int64

In [22]:
# Standardise active status
active_text = (
    df_clean["is_active"]
    .astype("string")
    .str.strip()
    .str.lower()
)

active_mapping = {
    "true": True,
    "1": True,
    "yes": True,
    "y": True,
    "false": False,
    "0": False,
    "no": False,
    "n": False
}

df_clean["is_active"] = active_text.map(active_mapping).astype("boolean")

print("Active status counts:")
print(df_clean["is_active"].value_counts(dropna=False))
print("\nData type:", df_clean["is_active"].dtype)

Active status counts:
is_active
False    503
True     496
Name: count, dtype: Int64

Data type: boolean

In [23]:
# Standardise customer names
df_clean["full_name"] = (
    df_clean["full_name"]
    .astype("string")
    .str.strip()
    .str.title()
)

# Standardise email addresses
df_clean["email"] = (
    df_clean["email"]
    .astype("string")
    .str.strip()
    .str.lower()
)

print("Sample standardised names:")
print(df_clean["full_name"].head(10))

print("\nSample standardised emails:")
print(df_clean["email"].head(10))

Sample standardised names:
0       Aisha Brennan
1        Omar Brennan
2         Ravi Okafor
3    Leilani Da Silva
4     Marcus Kowalski
5      Leilani Odwyer
6        Tomás Odwyer
7         Priya Costa
8        Ana Nakamura
9         Yuki Nguyen
Name: full_name, dtype: string

Sample standardised emails:
0         aisha.brennan@mail.test
1        omar.brennan@example.com
2             ravi[at]example.com
3    leilani.dasilva@corp.example
4     marcus.kowalski@example.com
5      leilani.odwyer@example.com
6        toms.odwyer@corp.example
7           priya.costa@mail.test
8          ana.nakamura@mail.test
9         yuki.nguyen@example.com
Name: email, dtype: string

In [24]:
# Convert mixed date formats into datetime
df_clean["signup_date"] = pd.to_datetime(
    df_clean["signup_date"],
    format="mixed",
    errors="coerce"
)

print("Signup date data type:", df_clean["signup_date"].dtype)
print("\nEarliest signup date:", df_clean["signup_date"].min())
print("Latest signup date:", df_clean["signup_date"].max())
print("Missing signup dates:", df_clean["signup_date"].isna().sum())

Signup date data type: datetime64[ns]

Earliest signup date: 2023-01-01 00:00:00
Latest signup date: 2025-11-04 00:00:00
Missing signup dates: 54

In [25]:
# Standardise customer IDs
df_clean["customer_id"] = (
    df_clean["customer_id"]
    .astype("string")
    .str.strip()
)

print("Customer ID data type:", df_clean["customer_id"].dtype)
print("\nSample customer IDs:")
print(df_clean["customer_id"].head(10))

Customer ID data type: string

Sample customer IDs:
0    CUST-1387
1    CUST-1943
2    CUST-1007
3    CUST-1249
4    CUST-1900
5    CUST-1841
6    CUST-1433
7    CUST-1194
8    CUST-1466
9    CUST-1116
Name: customer_id, dtype: string

In [26]:
# Find customer IDs that appear more than once
repeated_ids = df_clean["customer_id"].value_counts()
repeated_ids = repeated_ids[repeated_ids > 1]

print("Number of customer IDs appearing more than once:", len(repeated_ids))
print("\nMost frequently repeated IDs:")
print(repeated_ids.head(10))

print("\nExample records for repeated IDs:")
print(
    df_clean[df_clean["customer_id"].isin(repeated_ids.index)]
    [["customer_id", "full_name", "email", "signup_date"]]
    .head(15)
)

Number of customer IDs appearing more than once: 42

Most frequently repeated IDs:
customer_id
CUST-1039        2
CUST-1063        2
CUST-1584        2
CUST-1694        2
CUST-00001302    2
CUST-1040        2
CUST-1518        2
CUST-00001157    2
CUST-1639        2
CUST-1313        2
Name: count, dtype: Int64

Example records for repeated IDs:
       customer_id        full_name                       email signup_date
17   CUST-00001273    Grace Ferrari     grace.ferrari@mail.test  2025-04-19
26       CUST-1324     Mikael Patel    mikael.patel@example.com  2023-06-21
47       CUST-1685       Ravi Costa     ravi.costa@corp.example  2024-02-09
51       CUST-1045    Yuki Nakamura  yuki.nakamura@corp.example  2025-04-28
62       CUST-1694   Marcus Ferrari    marcus.ferrari@mail.test  2025-06-14
64       CUST-1040   Mikael Brennan    mikael.brennan@mail.test  2024-09-28
71       CUST-1161   Aisha Kowalski        aisha[at]example.com  2023-05-16
85       CUST-1161   Aisha Kowalski        aisha[at]example.com  2023-05-16
87       CUST-1063     Priya Odwyer   priya.odwyer@corp.example  2025-04-28
103      CUST-1037    Mikael Odwyer  mikael.odwyer@corp.example  2023-04-18
128  CUST-00001471  Priya Lindqvist   priya.lindqvist@mail.test  2023-12-29
131      CUST-1584    Noor Kowalski  noor.kowalski@corp.example  2023-01-07
136      CUST-1313      Chen Haddad    chen.haddad@corp.example         NaT
140  CUST-00001104       Omar Weber     omar.weber@corp.example  2023-11-19
150      CUST-1039       Omar Costa        omar.costa@mail.test  2024-06-03

In [27]:
# Check for exact duplicate rows after standardisation
duplicate_rows = df_clean[df_clean.duplicated(keep=False)]

print("Rows involved in exact duplicates:", len(duplicate_rows))
print("\nExact duplicate records:")
print(duplicate_rows.sort_values("customer_id").head(10))

Rows involved in exact duplicates: 84

Exact duplicate records:
       customer_id      full_name                     email signup_date  \
140  CUST-00001104     Omar Weber   omar.weber@corp.example  2023-11-19
564  CUST-00001104     Omar Weber   omar.weber@corp.example  2023-11-19
284  CUST-00001157    Ravi Nguyen  ravi.nguyen@corp.example  2023-03-23
783  CUST-00001157    Ravi Nguyen  ravi.nguyen@corp.example  2023-03-23
886  CUST-00001215   Marcus Costa  marcus.costa@example.com  2025-05-16
397  CUST-00001215   Marcus Costa  marcus.costa@example.com  2025-05-16
17   CUST-00001273  Grace Ferrari   grace.ferrari@mail.test  2025-04-19
251  CUST-00001273  Grace Ferrari   grace.ferrari@mail.test  2025-04-19
703  CUST-00001298    Jonas Patel   jonas.patel@example.com  2024-06-05
546  CUST-00001298    Jonas Patel   jonas.patel@example.com  2024-06-05

            country   spend         segment  is_active
140         Germany  268.81      Mid-Market       True
564         Germany  268.81      Mid-Market       True
284          Brazil  100.44      Enterprise       True
783          Brazil  100.44      Enterprise       True
886  United Kingdom   540.0      Enterprise       True
397  United Kingdom   540.0      Enterprise       True
17    United States   238.7  Small Business      False
251   United States   238.7  Small Business      False
703   United States   77.01      Enterprise      False
546   United States   77.01      Enterprise      False

In [28]:
# Remove exact duplicates revealed by standardisation
rows_before = len(df_clean)

df_clean = df_clean.drop_duplicates().copy()

rows_after = len(df_clean)

print("Rows before removal:", rows_before)
print("Rows after removal:", rows_after)
print("Additional duplicate rows removed:", rows_before - rows_after)
print("Remaining exact duplicates:", df_clean.duplicated().sum())

Rows before removal: 999
Rows after removal: 957
Additional duplicate rows removed: 42
Remaining exact duplicates: 0

### Data Cleaning Decisions

1. **Exact duplicates:** Removed exact duplicate records after standardising the data. The initial dataset contained 1,000 rows. One exact duplicate was removed initially, and 42 additional duplicate rows became identifiable after standardisation, leaving 957 rows.

2. **Missing email addresses:** Retained missing values because email addresses cannot be reliably inferred from other fields.

3. **Missing signup dates:** Retained missing values because the original dates are unknown and should not be invented.

4. **Missing spending values:** Converted placeholders (`none`, `-`, and `-999`) to missing values, then filled missing spending with the median of the valid, outlier-capped spending values.

5. **Spending outliers:** Detected outliers using the IQR method. Values above the upper IQR boundary were capped at approximately 1,381.03 to reduce the influence of extreme observations without deleting customer records. This is a statistical treatment, not proof that every flagged value was erroneous.

6. **Country names:** Standardised country variants into United States, United Kingdom, Germany, Brazil, and France.

7. **Customer segments:** Standardised segment labels into Consumer, Small Business, Enterprise, and Mid-Market.

8. **Active status:** Converted variations such as `Y`, `yes`, `1`, and `true` into Boolean `True`; variations such as `N`, `no`, `0`, and `false` into Boolean `False`.

9. **Names and emails:** Trimmed extra spaces, converted names to title case, and converted email addresses to lowercase. Email validity still requires separate validation.

10. **Data types:** Converted customer IDs to strings, signup dates to datetime, spending to numeric, and active status to Boolean.

In [29]:
# Identify emails that do not match a basic email format
email_pattern = r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$"

has_email = df_clean["email"].notna()

invalid_emails = df_clean.loc[
    has_email & ~df_clean["email"].str.match(email_pattern, na=False),
    ["customer_id", "full_name", "email"]
]

print("Non-missing emails checked:", has_email.sum())
print("Invalid email formats found:", len(invalid_emails))
print("\nExamples of invalid emails:")
print(invalid_emails.head(15))

Non-missing emails checked: 926
Invalid email formats found: 59

Examples of invalid emails:
       customer_id       full_name                        email
2        CUST-1007     Ravi Okafor          ravi[at]example.com
43       CUST-1927     Yuki Haddad      yuki <yuki@example.com>
71       CUST-1161  Aisha Kowalski         aisha[at]example.com
74       CUST-1946  Marcus Ferrari  marcus <marcus@example.com>
93   CUST-00001549   Jonas Ferrari         jonas[at]example.com
120      CUST-1003   Yuki Nakamura      yuki <yuki@example.com>
133  CUST-00001827     Priya Weber         priya[at]example.com
137      CUST-1357    Sofia Okafor    sofia <sofia@example.com>
154      CUST-1639  Priya Nakamura         priya[at]example.com
161  CUST-00001862   Leilani Costa        leilani@@example..com
173  CUST-00001558   Mikael Odwyer  mikael <mikael@example.com>
203      CUST-1826   Sofia Brennan         sofia[at]example.com
209      CUST-1691  Aisha Nakamura          aisha@@example..com
224  CUST-00001799   Aisha Brennan    aisha <aisha@example.com>
225  CUST-00001167    Ana Nakamura            ana@@example..com

In [30]:
# Extract clearly identifiable email addresses inside angle brackets
wrapped_email = df_clean["email"].str.extract(r"<([^<>]+)>", expand=False)

df_clean["email"] = df_clean["email"].where(
    wrapped_email.isna(),
    wrapped_email
)

# Recheck email formats
email_pattern = r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$"

has_email = df_clean["email"].notna()

invalid_emails = df_clean.loc[
    has_email & ~df_clean["email"].str.match(email_pattern, na=False),
    ["customer_id", "full_name", "email"]
]

print("Remaining invalid email formats:", len(invalid_emails))
print("\nExamples:")
print(invalid_emails.head(10))

Remaining invalid email formats: 38

Examples:
       customer_id       full_name                  email
2        CUST-1007     Ravi Okafor    ravi[at]example.com
71       CUST-1161  Aisha Kowalski   aisha[at]example.com
93   CUST-00001549   Jonas Ferrari   jonas[at]example.com
133  CUST-00001827     Priya Weber   priya[at]example.com
154      CUST-1639  Priya Nakamura   priya[at]example.com
161  CUST-00001862   Leilani Costa  leilani@@example..com
203      CUST-1826   Sofia Brennan   sofia[at]example.com
209      CUST-1691  Aisha Nakamura    aisha@@example..com
225  CUST-00001167    Ana Nakamura      ana@@example..com
241      CUST-1902   Noor Nakamura    noor[at]example.com

In [31]:
# Mark unresolved invalid email formats as missing
email_pattern = r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$"

has_email = df_clean["email"].notna()

invalid_mask = has_email & ~df_clean["email"].str.match(
    email_pattern, na=False
)

invalid_count = int(invalid_mask.sum())

df_clean.loc[invalid_mask, "email"] = pd.NA

print("Invalid email formats marked missing:", invalid_count)
print("Missing emails after cleaning:", df_clean["email"].isna().sum())
print("Invalid non-missing emails remaining:", (
    df_clean["email"].notna()
    & ~df_clean["email"].str.match(email_pattern, na=False)
).sum())

Invalid email formats marked missing: 38
Missing emails after cleaning: 69
Invalid non-missing emails remaining: 0

In [32]:
# Review the current dataset quality
print("Dataset shape:", df_clean.shape)

print("\nMissing values per column:")
print(df_clean.isna().sum())

print("\nData types:")
print(df_clean.dtypes)

print("\nExact duplicate rows:", df_clean.duplicated().sum())

Dataset shape: (957, 8)

Missing values per column:
customer_id     0
full_name       0
email          69
signup_date    53
country         0
spend           0
segment         0
is_active       0
dtype: int64

Data types:
customer_id    string[python]
full_name      string[python]
email          string[python]
signup_date    datetime64[ns]
country        string[python]
spend                 Float64
segment        string[python]
is_active             boolean
dtype: object

Exact duplicate rows: 0

In [33]:
# Create before-and-after data quality report

quality_report = pd.DataFrame({
    "Metric": [
        "Row count",
        "Total missing values",
        "Exact duplicate rows",
        "Columns with correct target data types"
    ],
    "Before cleaning": [
        len(df),
        int(df.isna().sum().sum()),
        int(df.duplicated().sum()),
        0
    ],
    "After cleaning": [
        len(df_clean),
        int(df_clean.isna().sum().sum()),
        int(df_clean.duplicated().sum()),
        int(
            df_clean["customer_id"].dtype == "string"
            and pd.api.types.is_datetime64_any_dtype(df_clean["signup_date"])
            and pd.api.types.is_numeric_dtype(df_clean["spend"])
            and pd.api.types.is_bool_dtype(df_clean["is_active"])
        ) * 4
    ]
})

quality_report

                                   Metric  Before cleaning  After cleaning
0                               Row count             1000             957
1                    Total missing values              100             122
2                    Exact duplicate rows                1               0
3  Columns with correct target data types                0               4

In [34]:
# Save the cleaned dataset
output_file = "PrajwalPoojary_Task3_Cleaned.csv"

df_clean.to_csv(output_file, index=False)

print("Cleaned dataset saved as:", output_file)
print("Rows saved:", len(df_clean))
print("Columns saved:", len(df_clean.columns))

Cleaned dataset saved as: PrajwalPoojary_Task3_Cleaned.csv
Rows saved: 957
Columns saved: 8

In [35]:
# Reload and validate the saved CSV
saved_df = pd.read_csv("PrajwalPoojary_Task3_Cleaned.csv")

print("Saved file shape:", saved_df.shape)
print("\nMissing values in saved file:")
print(saved_df.isna().sum())

print("\nExact duplicate rows:", saved_df.duplicated().sum())
print("\nFirst five rows:")
print(saved_df.head())

Saved file shape: (957, 8)

Missing values in saved file:
customer_id     0
full_name       0
email          69
signup_date    53
country         0
spend           0
segment         0
is_active       0
dtype: int64

Exact duplicate rows: 0

First five rows:
  customer_id         full_name                         email signup_date  \
0   CUST-1387     Aisha Brennan       aisha.brennan@mail.test         NaN
1   CUST-1943      Omar Brennan      omar.brennan@example.com  2025-01-25
2   CUST-1007       Ravi Okafor                           NaN  2024-10-18
3   CUST-1249  Leilani Da Silva  leilani.dasilva@corp.example  2024-06-26
4   CUST-1900   Marcus Kowalski   marcus.kowalski@example.com  2024-09-26

          country   spend     segment  is_active
0         Germany  252.99  Enterprise      False
1  United Kingdom  100.66  Enterprise      False
2          Brazil  273.67  Enterprise       True
3  United Kingdom   84.38  Mid-Market       True
4         Germany  252.99  Mid-Market       True